name: example
description: "MyBoxy UI and UX for being used by MyBoxy Main App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  my_boxy_ds:
    path: ../
  flutter_lucide: ^1.41.0
  flutter_svg: ^2.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - ../assets/images/ic_mastercard.png
    - ../assets/images/ic_mastercard.svg

  fonts:
    - family: Lexend
      fonts:
        - asset: ../assets/fonts/Lexend-Thin.ttf
        - asset: ../assets/fonts/Lexend-SemiBold.ttf
        - asset: ../assets/fonts/Lexend-Medium.ttf
        - asset: ../assets/fonts/Lexend-Black.ttf
        - asset: ../assets/fonts/Lexend-Bold.ttf
        - asset: ../assets/fonts/Lexend-ExtraBold.ttf
        - asset: ../assets/fonts/Lexend-ExtraLight.ttf
        - asset: ../assets/fonts/Lexend-Light.ttf
        - asset: ../assets/fonts/Lexend-Regular.ttf
    - family: SFMono
      fonts:
        - asset: ../assets/fonts/SFMonoBold.otf
        - asset: ../assets/fonts/SFMonoBoldItalic.otf
        - asset: ../assets/fonts/SFMonoRegular.otf
        - asset: ../assets/fonts/SFMonoRegularItalic.otf
        - asset: ../assets/fonts/SFMonoSemiBold.otf
        - asset: ../assets/fonts/SFMonoSemiBoldItalic.otf
        - asset: ../assets/fonts/SFMonoLight.otf
        - asset: ../assets/fonts/SFMonoLightItalic.otf
        - asset: ../assets/fonts/SFMonoMedium.otf
        - asset: ../assets/fonts/SFMonoMediumItalic.otf
        - asset: ../assets/fonts/SFMonoHeavyItalic.otf
        - asset: ../assets/fonts/SFMonoHeavy.otf